spring.application.name=hospital_management_system
spring.datasource.url=jdbc:postgresql://localhost:5432/hostpitalDB

server.servlet.context-path=/api/v1

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

logging.level.org.springframework.orm.jpa=OFF
logging.level.com.zaxxer.hikari=OFF

# Activate dev profile
spring.profiles.active=dev